# Generated by Django 2.1.1 on 2020-01-16 10:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import projet_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projet_app.models.reference_file_naming)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='TranslationOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('full_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000)])),
                ('treated', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('treated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=projet_app.models.request_file_naming)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_app.TranslationCategory')),
                ('dest_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_requests', to='projet_app.Language')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projet_app.models.response_file_naming)),
                ('done', models.BooleanField(default=False)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_app.TranslationOffer')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_translations', models.IntegerField(default=0)),
                ('cv', models.FileField(upload_to=projet_app.models.cv_file_naming)),
                ('is_assermented', models.BooleanField(default=False)),
                ('assermented_file', models.FileField(blank=True, upload_to=projet_app.models.assermented_file_naming)),
                ('global_rate', models.IntegerField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='translator', to='projet_app.TranslationCategory')),
                ('languages', models.ManyToManyField(related_name='translator', to='projet_app.Language')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to=projet_app.models.profile_pic_naming)),
                ('wilaya', models.CharField(max_length=30)),
                ('commune', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Warn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warn_text', models.TextField()),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_app.TranslatorProfile')),
                ('warner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_app.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='translatorprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translator_profile', to='projet_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='src_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_requests', to='projet_app.Language'),
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='translator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projet_app.TranslatorProfile'),
        ),
        migrations.AddField(
            model_name='translationoffer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_app.TranslationRequest'),
        ),
        migrations.AddField(
            model_name='referencefile',
            name='translator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_app.TranslatorProfile'),
        ),
        migrations.AddField(
            model_name='rate',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='rate',
            name='translator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_app.TranslatorProfile'),
        ),
    ]
