# Generated by Django 2.1.1 on 2020-01-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translationcategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='translationcategory',
            name='description',
            field=models.TextField(default='zapdos'),
            preserve_default=False,
        ),
    ]
