# Generated by Django 2.1.1 on 2020-01-16 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projet_app', '0002_auto_20200116_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationoffer',
            name='offer_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='translationresponse',
            name='response_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
