# Generated by Django 2.1.1 on 2020-01-13 10:53

from django.db import migrations, models
import projet_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_app', '0003_auto_20200113_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=projet_app.models.profile_pic_naming),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
