# Generated by Django 2.1.1 on 2020-01-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_app', '0004_auto_20200118_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translationoffer',
            old_name='full_price',
            new_name='after_price',
        ),
        migrations.AlterField(
            model_name='translationoffer',
            name='accept_offer_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
