# Generated by Django 2.1.1 on 2020-01-13 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet_app', '0004_auto_20200113_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatorprofile',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projet_app.UserProfile'),
            preserve_default=False,
        ),
    ]
