# Generated by Django 2.1.1 on 2020-01-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_app', '0005_auto_20200118_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationoffer',
            name='accept_offer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
