# Generated by Django 2.1.1 on 2020-01-13 11:10

from django.db import migrations, models
import projet_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_app', '0005_translatorprofile_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatorprofile',
            name='assermented_file',
            field=models.FileField(blank=True, upload_to=projet_app.models.request_file_naming),
        ),
    ]
