# Generated by Django 2.1.1 on 2020-01-19 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet_app', '0006_auto_20200118_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencefile',
            name='translator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_files', to='projet_app.TranslatorProfile'),
        ),
    ]
