# Generated by Django 2.1.1 on 2020-01-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet_app', '0007_auto_20200119_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warn',
            old_name='translator',
            new_name='warned_against',
        ),
    ]
