# Generated by Django 2.1.1 on 2020-01-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_app', '0007_auto_20200113_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatorprofile',
            name='global_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translatorprofile',
            name='categories',
            field=models.ManyToManyField(related_name='translator', to='projet_app.TranslationCategory'),
        ),
        migrations.AlterField(
            model_name='translatorprofile',
            name='languages',
            field=models.ManyToManyField(related_name='translator', to='projet_app.Language'),
        ),
    ]
