# Generated by Django 2.1.1 on 2020-01-20 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet_app', '0008_auto_20200120_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warn',
            name='warned_against',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warns_against_set', to='projet_app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='warn',
            name='warner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warns_from_set', to='projet_app.UserProfile'),
        ),
    ]
